import {
  SkillCategoryEnum,
  SkillData,
} from "../../data-model/item-data/skillData";
import { ItemTypeEnum } from "../../data-model/item-data/itemTypes";

// All default skills that are have a base chance > 0.
// Base Chance 0 skills (skills you have to learn to use) go into a compendium (packs/skills.db).
const characterSkills: ItemData<SkillData>[] = [
  // *** Agility ***
  {
    name: "Boat",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Boat",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Climb",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Climb",
      specialization: "",
      baseChance: 40,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Dodge",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Dodge",
      specialization: "",
      baseChance: 1,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Drive",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Drive",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Jump",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Jump",
      specialization: "",
      baseChance: 1,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Ride (all)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Ride",
      specialization: "all",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Swim",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Agility,
      skillName: "Swim",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Communication ***
  {
    name: "Act",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Act",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Art",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Art",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Bargain",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Bargain",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Charm",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Charm",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Dance",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Dance",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Disguise",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Disguise",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Fast Talk",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Fast Talk",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Intimidate",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Intimidate",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Intrigue",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Intrigue",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Orate",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Orate",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Sing",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Sing",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Speak (...)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Communication,
      skillName: "Speak",
      specialization: "...",
      baseChance: 50,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Knowledge ***
  {
    name: "Animal Lore",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Animal Lore",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Battle",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Battle",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Celestial Lore",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Celestial Lore",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
    },
  },
  {
    name: "Customs (local)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Customs",
      specialization: "local",
      baseChance: 25,
      learnedChance: 0,
    },
  },
  {
    name: "Elder Race Lore",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Elder Race Lore",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
    },
  },
  {
    name: "Evaluate",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Evaluate",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Farm",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Farm",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "First Aid",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "First Aid",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Game",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Game",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Herd",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Herd",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Homeland Lore (own)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Homeland Lore",
      specialization: "own",
      baseChance: 30,
      learnedChance: 0,
    },
  },
  {
    name: "Manage Household",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Manage Household",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Mineral Lore",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Mineral Lore",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
    },
  },
  {
    name: "Peaceful Cut",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Peaceful Cut",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Plant Lore",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Plant Lore",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
    },
  },
  {
    name: "Survival",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Survival",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Treat Disease",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Treat Disease",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Treat Poison",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Knowledge,
      skillName: "Treat Poison",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  // *** Magic ***
  {
    name: "Prepare Corpse",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Magic,
      skillName: "Prepare Corpse",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Spirit Combat",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Magic,
      skillName: "Spirit Combat",
      specialization: "",
      baseChance: 20,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Spirit Travel",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Magic,
      skillName: "Spirit Travel",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Worship (...)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Magic,
      skillName: "Worship",
      specialization: "...",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Manipulation ***
  {
    name: "Conceal",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Manipulation,
      skillName: "Conceal",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Devise",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Manipulation,
      skillName: "Devise",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Sleight",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Manipulation,
      skillName: "Sleight",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Perception ***
  {
    name: "Insight (own species)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Perception,
      skillName: "Insight",
      specialization: "own species",
      baseChance: 20,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Listen",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Perception,
      skillName: "Listen",
      specialization: "",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Scan",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Perception,
      skillName: "Scan",
      specialization: "",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Search",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Perception,
      skillName: "Search",
      specialization: "",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Track",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Perception,
      skillName: "Track",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Perception ***
  {
    name: "Hide",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Stealth,
      skillName: "Hide",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Move Quietly",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Stealth,
      skillName: "Move Quietly",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Melee Weapons ***
  {
    name: "1H Axe (small)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Axe",
      specialization: "small",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Axe (battle)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Axe",
      specialization: "battle",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Axe (battle)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Axe",
      specialization: "battle",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Axe (great)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Axe",
      specialization: "great",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Axe (dagger)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Axe",
      specialization: "dagger",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Dagger",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "Dagger",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Dagger (parrying)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "Dagger",
      specialization: "parrying",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Dagger (throwing)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "Dagger",
      specialization: "throwing",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Sword (broadsword)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Sword",
      specialization: "broadsword",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Sword (kopis)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Sword",
      specialization: "kopis",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Sword (rapier)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Sword",
      specialization: "rapier",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Sword (shortsword)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Sword",
      specialization: "shortsword",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Sword (greatsword)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Sword",
      specialization: "greatsword",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Sword (rhomphaia)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Sword",
      specialization: "rhomphaia",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Sword (sickle-sword)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Sword",
      specialization: "sickle-sword",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Hammer (warhammer)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Hammer",
      specialization: "warhammer",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Hammer (greathammer)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Hammer",
      specialization: "greathammer",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Hammer (maul)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Hammer",
      specialization: "maul",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Mace (light)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Mace",
      specialization: "light",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Mace (heavy)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Mace",
      specialization: "heavy",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Mace (singlestick)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Mace",
      specialization: "singlestick",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Mace (club)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Mace",
      specialization: "club",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Mace (mace)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Mace",
      specialization: "mace",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Mace (quarterstaff)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Mace",
      specialization: "quarterstaff",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Spear (javelin)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Spear",
      specialization: "javelin",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Spear (short)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Spear",
      specialization: "short",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "1H Spear (lance)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "1H Spear",
      specialization: "lance",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Spear (pike)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Spear",
      specialization: "pike",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Spear (long)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Spear",
      specialization: "long",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "2H Spear (short)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MeleeWeapons,
      skillName: "2H Spear",
      specialization: "short",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Missile Weapons ***
  {
    name: "Bow (composite)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Bow",
      specialization: "composite",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Bow (elf)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Bow",
      specialization: "elf",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Bow (self)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Bow",
      specialization: "self",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Crossbow (light)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Crossbow",
      specialization: "light",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Crossbow (heavy)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Crossbow",
      specialization: "heavy",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Crossbow (repeating)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Crossbow",
      specialization: "repeating",
      baseChance: 25,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Atlatl",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Atlatl",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Javelin (dart)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Javelin",
      specialization: "dart",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Javelin (javelin)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Javelin",
      specialization: "javelin",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Javelin (shortspear)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Javelin",
      specialization: "Javelin",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Lasso (pole)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Lasso",
      specialization: "pole",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Throwing Axe",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Throwing Axe",
      specialization: "",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Throwing Dagger",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Throwing Dagger",
      specialization: "",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Rock",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Rock",
      specialization: "",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Sling (sling)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Sling",
      specialization: "sling",
      baseChance: 5,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Sling (staff)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.MissileWeapons,
      skillName: "Sling",
      specialization: "staff",
      baseChance: 10,
      learnedChance: 0,
      experience: false,
    },
  },

  // *** Shields ***
  {
    name: "Shield (small)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Shields,
      skillName: "Shield",
      specialization: "small",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Shield (medium)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Shields,
      skillName: "Shield",
      specialization: "medium",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
  {
    name: "Shield (large)",
    type: ItemTypeEnum.Skill,
    img: "icons/svg/mystery-man.svg",
    flags: {},
    data: {
      category: SkillCategoryEnum.Shields,
      skillName: "Shield",
      specialization: "large",
      baseChance: 15,
      learnedChance: 0,
      experience: false,
    },
  },
];

export default characterSkills;
