import { ItemTypeEnum } from "../../data-model/item-data/itemTypes";
import { RuneData, RuneTypeEnum } from "../../data-model/item-data/runeData";

const powerFormRunes: ItemData<RuneData>[] = [
  {
    name: "Man (form)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Man",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Form,
      opposingRune: "Beast (form)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/man.svg",
  },
  {
    name: "Beast (form)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Beast",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Form,
      opposingRune: "Man (form)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/beast.svg",
  },
  {
    name: "Fertility (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Fertility",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Death (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/fertility.svg",
  },
  {
    name: "Death (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Death",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Fertility (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/death.svg",
  },
  {
    name: "Harmony (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Harmony",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Disorder (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/harmony.svg",
  },
  {
    name: "Disorder (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Disorder",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Harmony (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/disorder.svg",
  },
  {
    name: "Truth (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Truth",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Illusion (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/truth.svg",
  },
  {
    name: "Illusion (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Illusion",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Truth (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/illusion.svg",
  },
  {
    name: "Stasis (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Stasis",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Movement (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/stasis.svg",
  },
  {
    name: "Movement (power)",
    type: ItemTypeEnum.Rune,
    data: {
      rune: "Movement",
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: "Stasis (power)",
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/movement_change.svg",
  },
];

export default powerFormRunes;
