import { ItemTypeEnum } from "../../data-model/item-data/itemTypes";
import {
  RuneData,
  RuneEnum,
  RuneTypeEnum,
} from "../../data-model/item-data/runeData";

const powerFormRunes: ItemData<RuneData>[] = [
  {
    name: RuneEnum.Man,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Form,
      opposingRune: RuneEnum.Beast,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/man.svg",
  },
  {
    name: RuneEnum.Beast,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Form,
      opposingRune: RuneEnum.Man,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/beast.svg",
  },
  {
    name: RuneEnum.Fertility,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Death,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/fertility.svg",
  },
  {
    name: RuneEnum.Death,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Fertility,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/death.svg",
  },
  {
    name: RuneEnum.Harmony,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Disorder,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/harmony.svg",
  },
  {
    name: RuneEnum.Disorder,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Harmony,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/disorder.svg",
  },
  {
    name: RuneEnum.Truth,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Illusion,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/truth.svg",
  },
  {
    name: RuneEnum.Illusion,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Truth,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/illusion.svg",
  },
  {
    name: RuneEnum.Stasis,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Movement,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/stasis.svg",
  },
  {
    name: RuneEnum.Movement,
    type: ItemTypeEnum.Rune,
    data: {
      chance: 50,
      experience: false,
      description: "Se RQG p.xx",
      runeType: RuneTypeEnum.Power,
      opposingRune: RuneEnum.Stasis,
      minorRunes: [],
      isMastered: false,
    },
    flags: {},
    img: "systems/rqg/assets/icons/runes/movement_change.svg",
  },
];

export default powerFormRunes;
