env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "prettier"
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": "off" # allow until foundry types are updated
  "prettier/prettier": "error"
  curly:
    - error
    - all
