export const hitLocationNamesObject = {
  hitLocationItemNames: [
    "Abdomen",
    "Chest",
    "Head",
    "Left Arm",
    "Left Leg",
    "Right Arm",
    "Right Leg",
    "Body",
    "Forebody",
    "Forequarter",
    "Hindquarter",
    "Left Center Front Leg",
    "Left Center Leg",
    "Left Center Rear Leg",
    "Left Foreleg",
    "Left Head",
    "Left Hind Leg",
    "Left Wing",
    "Right Center Front Leg",
    "Right Center Leg",
    "Right Center Rear Leg",
    "Right Foreleg",
    "Right Head",
    "Right Hind Leg",
    "Right Wing",
    "Shell",
    "Tail",
    "Tentacle 1",
    "Tentacle 2",
    "Tentacle 3",
    "Tentacle 4",
    "Tentacle 5",
    "Tentacle 6",
    "Tentacle 7",
    "Tentacle 8",
    "Thorax",
    "Trunk",
  ],
};
