export const hitLocationNamesObject = {
  hitLocationItemNames: [
    "Head",
    "Left Arm",
    "Right Arm",
    "Chest",
    "Abdomen",
    "Left Leg",
    "Right Leg",
    "Left Wing",
    "Right Wing",
    "Tail",
    "Left Hind Leg",
    "Right Hind Leg",
    "Hindquarter",
    "Forequarter",
    "Left Fore Leg",
    "Right Fore Leg",
    "Left Middle Leg",
    "Right Middle Leg",
    "Left Center Rear Leg",
    "Right Center Rear Leg",
    "Left Center Front Leg",
    "Right Center Front Leg",
    "Hind Body",
    "Mid Body",
    "Front Body",
    "Thorax",
    "Shell",
    "Left Head",
    "Right Head",
    "Body",
    "Trunk",
    "Tentacle 1",
    "Tentacle 2",
    "Tentacle 3",
    "Tentacle 4",
    "Tentacle 5",
    "Tentacle 6",
    "Tentacle 7",
    "Tentacle 8",
    "Left Claw",
    "Right Claw",
    "Left Hind Flipper",
    "Right Hind Flipper",
    "Left Fore Flipper",
    "Right Fore Flipper",
    "Left Paw",
    "Right Paw",
    "Left Pedipalp",
    "Right Pedipalp",
    "Neck",
    "Lower Left Arm",
    "Lower Right Arm",
  ],
};
