export const hitLocationNamesObject = {
  hitLocationItemNames: [
    "Abdomen",
    "Body",
    "Chest",
    "Forebody",
    "Forequarter",
    "Front Body",
    "Head",
    "Hind Body",
    "Hindquarter",
    "Left Arm",
    "Left Center Front Leg",
    "Left Center Leg",
    "Left Center Rear Leg",
    "Left Claw",
    "Left Fore Flipper",
    "Left Foreleg",
    "Left Head",
    "Left Hind Flipper",
    "Left Hind Leg",
    "Left Leg",
    "Left Middle Leg",
    "Left Paw",
    "Left Pedipalp",
    "Left Wing",
    "Lower Left Arm",
    "Lower Right Arm",
    "Mid Body",
    "Neck",
    "Right Arm",
    "Right Center Front Leg",
    "Right Center Leg",
    "Right Center Rear Leg",
    "Right Claw",
    "Right Fore Flipper",
    "Right Foreleg",
    "Right Head",
    "Right Hind Flipper",
    "Right Hind Leg",
    "Right Leg",
    "Right Middle Leg",
    "Right Paw",
    "Right Pedipalp",
    "Right Wing",
    "Shell",
    "Tail",
    "Tentacle 1",
    "Tentacle 2",
    "Tentacle 3",
    "Tentacle 4",
    "Tentacle 5",
    "Tentacle 6",
    "Tentacle 7",
    "Tentacle 8",
    "Thorax",
    "Trunk",
  ],
};
