export enum ContextMenuRunes {
  RollCard = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/luck.svg"></div>',
  RollQuick = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/luck.svg"></div>',
  ToggleExperience = '<div class="context-icon experienced"><img class="context-icon-img" src="systems/rqg/assets/runes/mastery.svg"></div>',
  Improve = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/mastery.svg"></div>',
  InitializeCharacteristics = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/fertility.svg"></div>',
  InitializeAllCharacteristics = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/fertility.svg"></div>',
  Edit = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/movement_change.svg"></div>',
  Delete = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/death.svg"></div>',
  ViewDescription = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/truth.svg"></div>',
  SetNotCarried = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/images/equipped/not_carried.svg"></div>',
  SetCarried = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/images/equipped/carried.svg"></div>',
  SetEquipped = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/images/equipped/equipped.svg"></div>',
  Split = '<div class="context-icon"><img class="context-icon-img" src="systems/rqg/assets/runes/separate.svg"></div>',
}
