export const testItems = {
  attunedTo: "",
  contains: [
    {
      attunedTo: "",
      contains: [
        {
          attunedTo: "",
          contains: [],
          description:
            "<p>These are like greaves, but protect the forearm, made out of padded leather</p>",
          encumbrance: 0,
          equippedStatus: "equipped",
          gmNotes: "",
          id: "usb4lsNHnRLDmX0c",
          isVirtual: false,
          isContainer: false,
          location: "under Armor",
          name: "Leather Vambraces  (Leather)",
          physicalItemType: "unique",
          price: {
            estimated: 0,
            real: 10,
          },
          quantity: 1,
        },
        {
          attunedTo: "",
          contains: [],
          description:
            "<p>Leather to protect the lower leg. They either &ldquo;spring&rdquo; into shape or are strapped on.</p>\n<p>Can be worn under any other armor, with a cumulative encumbrance penalty. Instead of leather, this could also be quilted or thick cloth. It has the same&nbsp;qualities as described for leather&nbsp;</p>",
          encumbrance: 0.5,
          equippedStatus: "equipped",
          gmNotes: "",
          id: "yD3LiqU8rKv8yW1P",
          isVirtual: false,
          isContainer: false,
          location: "under Armor",
          name: "Leather Greaves  (Leather)",
          physicalItemType: "unique",
          price: {
            estimated: 0,
            real: 15,
          },
          quantity: 1,
        },
      ],
      description: "",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "virtual:equipped:under Armor",
      isVirtual: true,
      isContainer: true,
      location: "",
      name: "under Armor",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [
        {
          attunedTo: "",
          contains: [
            {
              attunedTo: "",
              contains: [],
              description:
                '<section class="secret gm-secret">\n<p>Flawed dead crystal/Gem&nbsp; &nbsp;Value:46L</p>\n</section>',
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "",
              id: "sYZQvfM8xUUB4SCK",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Green Crystal (001)",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 0,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: null,
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>Semi-precious White stone unpowered (69-72)</p>",
              id: "2iDIddO75JYf3pHO",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "White stone",
              physicalItemType: "unique",
              price: {
                estimated: 200,
                real: 1,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: null,
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>Flawed yellow stone unpowered (45-47)</p>",
              id: "StPcfMyAsE5XBXvZ",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Yellow stone",
              physicalItemType: "unique",
              price: {
                estimated: 60,
                real: 59,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "",
              id: "8bXE4wnw2x4k5xIZ",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Juwlery X25",
              physicalItemType: "unique",
              price: {
                estimated: 2400,
                real: 2400,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "",
              id: "yhaiwP709wdQCfqZ",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Juwlery x26",
              physicalItemType: "unique",
              price: {
                estimated: 3500,
                real: 2600,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "",
              id: "1gMonRQJ6QkQ1esw",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Juwlery x27",
              physicalItemType: "unique",
              price: {
                estimated: 50000,
                real: 600,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>Good Red Red CRYSTAL unpowered (25)</p>",
              id: "zXULpTSS29qm80KV",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Red stone x28",
              physicalItemType: "unique",
              price: {
                estimated: 70,
                real: 69,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>Good Light Blue stone unpowered (27)</p>",
              id: "HMjxQ1Hm6M4goGMs",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Blue stone x29",
              physicalItemType: "unique",
              price: {
                estimated: 50,
                real: 49,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: null,
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>Semi-precious&nbsp; Red ston (73-76)</p>",
              id: "jMqa0tXFNF8lvELV",
              isVirtual: false,
              isContainer: false,
              location: "Belt Pouch",
              name: "Red stone x30",
              physicalItemType: "unique",
              price: {
                estimated: 5,
                real: 4,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description:
                '<p><span style="font-size: 14px;">Costume jewelry that serves as a deed</span></p>',
              encumbrance: 0,
              equippedStatus: "carried",
              gmNotes: "<p>1-10L</p>",
              id: "NiGVLYhLusGq1YJh",
              isVirtual: false,
              isContainer: true,
              location: "Belt Pouch",
              name: "Costume Jewelery",
              physicalItemType: "currency",
              price: {
                estimated: 45,
                real: 45,
              },
              quantity: 1,
            },
          ],
          description: "<p>Belt Pouch capabel to hold 1 Enc</p>",
          encumbrance: 0,
          equippedStatus: "carried",
          gmNotes: "",
          id: "OLwQEIo1vhFdAWvg",
          isVirtual: false,
          isContainer: true,
          location: "Belt",
          name: "Belt Pouch",
          physicalItemType: "unique",
          price: {
            estimated: 0,
            real: 0.2,
          },
          quantity: 1,
        },
      ],
      description: "",
      encumbrance: 0,
      equippedStatus: "carried",
      gmNotes: "",
      id: "virtual:carried:Belt",
      isVirtual: true,
      isContainer: true,
      location: "",
      name: "Belt",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [
        {
          attunedTo: "",
          contains: [],
          description:
            "<p>These are plates molded to protect the lower leg.&nbsp;&nbsp;They either &ldquo;spring&rdquo; into shape or are strapped on. They are&nbsp;heavy and make sprinting difficult.</p>",
          encumbrance: 1,
          equippedStatus: "equipped",
          gmNotes: "",
          id: "ifk062JyG0wziIRs",
          isVirtual: false,
          isContainer: false,
          location: "armor",
          name: "Dragon Armor Greaves  (Dragon Hide and Scales)",
          physicalItemType: "unique",
          price: null,
          quantity: 1,
        },
        {
          attunedTo: "",
          contains: [],
          description:
            "<p>This armor covers the chest&nbsp;and abdomen and is made up of a cuirass and three or four&nbsp;sets of curved lower protection plates. The pieces are fastened&nbsp;together by thongs that allow movement.&nbsp;</p>",
          encumbrance: 3,
          equippedStatus: "equipped",
          gmNotes: "",
          id: "WfOQlBxEMTzKoQaN",
          isVirtual: false,
          isContainer: false,
          location: "armor",
          name: "Dragon Armor Hauberk  (Dragon Hide and Bone)",
          physicalItemType: "unique",
          price: null,
          quantity: 1,
        },
        {
          attunedTo: "",
          contains: [],
          description: "<p>These are like greaves, but protect the forearm.</p>",
          encumbrance: 1,
          equippedStatus: "equipped",
          gmNotes: "",
          id: "olzPns2WbDvtGEr5",
          isVirtual: false,
          isContainer: false,
          location: "armor",
          name: "Dragon Armor Vambraces  (Dragon Hide and Scales)",
          physicalItemType: "unique",
          price: null,
          quantity: 1,
        },
      ],
      description: "",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "virtual:equipped:armor",
      isVirtual: true,
      isContainer: true,
      location: "",
      name: "armor",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [
        {
          attunedTo: "Nisse",
          contains: [],
          description: "<h1>HEPP</h1>\n<p>Hubba bubba</p>\n<p>sq</p>",
          encumbrance: 2,
          equippedStatus: "carried",
          gmNotes: "",
          id: "b7KKpzicF7iiaWFQ",
          isVirtual: false,
          isContainer: true,
          location: "backen",
          name: "Shiny crystal",
          physicalItemType: "currency",
          price: {
            estimated: 20,
            real: 10,
          },
          quantity: 11,
        },
      ],
      description: "",
      encumbrance: 0,
      equippedStatus: "carried",
      gmNotes: "",
      id: "virtual:carried:backen",
      isVirtual: true,
      isContainer: true,
      location: "",
      name: "backen",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "<p>A long wooden stick, often used as a walking&nbsp;staff.</p>",
      encumbrance: 2,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "8Hu2fc0jk36Qi92W",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Quarterstaff",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 1,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description:
        "<p>A short-bladed weapon no more than 40 cm&nbsp;long. Daggers can be sharp on one or both edges, or be&nbsp;triangular in their cross-section if intended only for stabbing.&nbsp;</p>\n<p>They are often decorated. Most adults in Dragon Pass&nbsp;carry a dagger or knife. If thrown, use the Throwing Dagger&nbsp;skill.</p>",
      encumbrance: 0.25,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "W5bUaf9Hg61ZAM1y",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Dagger",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 10,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "<p>A broad-brimmed hat made of&nbsp;stout leather.</p>",
      encumbrance: 0.5,
      equippedStatus: "carried",
      gmNotes: "",
      id: "1EioaN5VZLp4VYzY",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Broad-brimmed Hat  (Leather)",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 4,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description:
        "<p>This close-fitting helmet has elongated&nbsp;cheek-pieces to protect the wearer&rsquo;s mouth and throat. A nose&nbsp;guard protects the nose and eyes. It offers excellent all-round&nbsp;protection but severely limits vision and hearing, as well as&nbsp;being hot and stuffy to wear for long periods.</p>\n<p>&nbsp;</p>",
      encumbrance: 1,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "Vc9wwC1qVkar4bGy",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Dragon Helm  (Dragon Hide and Scales)",
      physicalItemType: "unique",
      price: {
        estimated: null,
        real: null,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "<p>Fr&aring;n Barbarerna i fortet</p>",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "AuhWW0yzh3cXfRBO",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Silver armring",
      physicalItemType: "unique",
      price: {
        estimated: 50,
        real: 50,
      },
      quantity: 1,
    },
    {
      attunedTo: "Sandene",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "<p>MP storing crystal 9</p>",
      id: "XIdEoFUrhmi2Ct0G",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Red Crystal 9mp",
      physicalItemType: "consumable",
      price: {
        estimated: 0,
        real: 4500,
      },
      quantity: 9,
    },
    {
      attunedTo: "Sandene",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "<p>MP storing crystal 9</p>",
      id: "tLjqVmF6yvmrPE8w",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Blue Crystal 9mp",
      physicalItemType: "consumable",
      price: {
        estimated: 0,
        real: 4500,
      },
      quantity: "9",
    },
    {
      attunedTo: "",
      contains: [
        {
          attunedTo: "",
          contains: [
            {
              attunedTo: "",
              contains: [],
              description:
                '<p>Wood image of Etyries</p>\n<section class="secret gm-secret">\n<p>that adds +10% to Worship (Etyries).</p>\n</section>',
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "vAaxEpgS2ANAfxet",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Wood stauet",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 15,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 1,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "gA6WIvluiRKy2aDX",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Blanket (hide",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 2,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "<p>A bow drill and fire board.</p>",
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "d4rnVSjAw9mFcf5n",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Fire Starter",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 0.2,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "<p>1 Lunar</p>\n<p>160=1enc</p>",
              encumbrance: 0.0062,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "eEqVuEQLtkY6Lfpm",
              isVirtual: false,
              isContainer: true,
              location: "Backpack",
              name: "Lunars",
              physicalItemType: "currency",
              price: {
                estimated: 1,
                real: 1,
              },
              quantity: "449",
            },
            {
              attunedTo: "",
              contains: [],
              description: "<p>Scroll in Good Condition</p>",
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes:
                '<p><span style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; font-size: 12pt;">Scroll: Written in Esrolian/ Elasa Script</span><br style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; background-color: #ffffff;" /><span style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; font-size: 12pt;">Scroll of Great Knowledge</span><br style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; background-color: #ffffff;" /><span style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; font-size: 12pt;">Assiciated with Lankhor Mhy</span><br style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; background-color: #ffffff;" /><span style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; font-size: 12pt;">Magic Scroll and when read it will give the reader +15% Bonus in all Knowledge Skills</span></p>\n<p><span style="color: #3c4043; font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; letter-spacing: 0.2px; font-size: 12pt;">Value 3000L</span></p>',
              id: "EXiPEvCtCfjDP50I",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Scroll (X6)",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 500,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "EUbd4OxPBxzPkTNu",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Juwlery (c3)",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 130,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "Bx4UevFj87K7Sr0l",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Juwelery (c4)",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 100,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description:
                '<section class="gm-secret">\n<p><strong>A clear, fatty jelly substance with a faint and unpleasant&nbsp;smell of burnt meat</strong></p>\n</section>\n<section class="secret gm-secret">\n<p>When rubbed on the body, Rhino Fat provides one addi&middot;&nbsp;tional point of armor protection. Applying the fat takes ten&nbsp;minutes (plus the time to take off and put on the clothes worn&nbsp;over it) and once on, it will begin to wear off after one hour.&nbsp; &nbsp;By the end of five hours, the fat will be completely gone.&nbsp;</p>\n</section>',
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "SzgUep8142bt8eQs",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Jar with Rhino Fat",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 100,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description:
                '<p>The flounced and pleated bell-shaped&nbsp;skirt worn by noble women and priestesses.</p>\n<section class="secret gm-secret">\n<p>Price: 15&ndash;35 L depending on decoration and style.</p>\n</section>',
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "ckIxs5CYkhZ1R66P",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Dress, Esrolian",
              physicalItemType: "unique",
              price: {
                estimated: 0,
                real: 25,
              },
              quantity: 1,
            },
            {
              attunedTo: "",
              contains: [],
              description:
                "<p>The first coinage of the world was gold, brought to the&nbsp;people by the enigmatic Gold Wheel Dancers. In their honor,&nbsp;gold coins are still called wheels. Gold, however, is scarce&nbsp;and very valuable. One golden wheel equals 20 L. Gold is&nbsp;still mainly used as a means of settling debts between rulers&nbsp;rather than by individuals.</p>\n<p>100W = 1 Enc</p>",
              encumbrance: 0.01,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "JDdR2V2pNhmFGQMF",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Wheels",
              physicalItemType: "currency",
              price: {
                estimated: 20,
                real: 20,
              },
              quantity: 194,
            },
            {
              attunedTo: "",
              contains: [],
              description:
                "<p>The dwarves invented copper coins, but they were&nbsp;adopted by Issaries to facilitate trade between peoples. The&nbsp;copper coin is called a clack, or often just a copper. It takes&nbsp;ten clacks to equal one lunar.</p>\n<p>&nbsp; &nbsp; 160=1enc</p>",
              encumbrance: 0.00625,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "SqQSIJij90aS5PMe",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Clacks",
              physicalItemType: "currency",
              price: {
                estimated: 0.1,
                real: 0.1,
              },
              quantity: "0",
            },
            {
              attunedTo: "",
              contains: [],
              description: "",
              encumbrance: 0,
              equippedStatus: "notCarried",
              gmNotes: "",
              id: "5nVuDD1MrqNuFakq",
              isVirtual: false,
              isContainer: false,
              location: "Backpack",
              name: "Sleeping Drog POT:15",
              physicalItemType: "consumable",
              price: {
                estimated: 0,
                real: 500,
              },
              quantity: "2",
            },
          ],
          description: "",
          encumbrance: 1,
          equippedStatus: "notCarried",
          gmNotes: "",
          id: "TNR9fCbTgIXZaKol",
          isVirtual: false,
          isContainer: true,
          location: "Riding Horse",
          name: "Backpack",
          physicalItemType: "unique",
          price: {
            estimated: 0,
            real: 1,
          },
          quantity: 1,
        },
        {
          attunedTo: "",
          contains: [],
          description: "<p>Mechanical clock made by Remmie the Tinker in Brinespring Aggar</p>",
          encumbrance: 2,
          equippedStatus: "notCarried",
          gmNotes:
            "<p>This clock can measure time and is a wonder of tech.</p>\n<p>The Clock is valuble to Lhankor Mhy and Mostali, its requires a successful Device to operate.</p>",
          id: "xW4gkaqtKj37FW9x",
          isVirtual: false,
          isContainer: false,
          location: "Riding Horse",
          name: "Mechanic clock",
          physicalItemType: "unique",
          price: {
            estimated: 10,
            real: 50,
          },
          quantity: 1,
        },
        {
          attunedTo: "",
          contains: [],
          description: "<p>Aggar Beer</p>",
          encumbrance: 0.3,
          equippedStatus: "notCarried",
          gmNotes: "",
          id: "wpFe18rUbo15DD81",
          isVirtual: false,
          isContainer: false,
          location: "Riding Horse",
          name: "Small Keg  (liter)",
          physicalItemType: "consumable",
          price: {
            estimated: 0,
            real: 0,
          },
          quantity: 12,
        },
        {
          attunedTo: "",
          contains: [],
          description: "",
          encumbrance: 0,
          equippedStatus: "notCarried",
          gmNotes: "",
          id: "FUIi9O7oag36Lmgf",
          isVirtual: false,
          isContainer: false,
          location: "Riding Horse",
          name: "Armring",
          physicalItemType: "unique",
          price: {
            estimated: 0,
            real: 112,
          },
          quantity: 1,
        },
      ],
      description: "<p>@Actor[Q3cpiv5GdZslkHnJ]{Riding Horse}</p>",
      encumbrance: 30,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "UHP2sXZumDDjRY0f",
      isVirtual: false,
      isContainer: true,
      location: "",
      name: "Riding Horse",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description:
        '<p><span style="font-size: 14px;">The light crossbow is cocked by&nbsp;</span><span style="font-size: 14px;">hooking one end with a foot and using this as leverage in&nbsp;</span><span style="font-size: 14px;">cocking.</span></p>',
      encumbrance: 2,
      equippedStatus: "equipped",
      gmNotes: "",
      id: "HWyauKANACXUEg7f",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Light Crossbow.",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 80,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description:
        "<p>These Bolts have a vicious barbed tip,&nbsp;&nbsp;making them harder to remove. If an attack with them does impaling damage, removing it causes 1D4 additional damage.</p>",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes: "<p>Price: 10 L per dozen.</p>",
      id: "aGR485BMdDOJ7XXE",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Barbed Bolts",
      physicalItemType: "consumable",
      price: {
        estimated: 0,
        real: 10,
      },
      quantity: 9,
    },
    {
      attunedTo: "Danvis the Balck",
      contains: [],
      description:
        "<p>A silver crown with 3 Crystals, very stylish</p>\n<ul>\n<li>Protection 4 matrix</li>\n<li>21MP crystal</li>\n<li>spirit screen 4 matrix</li>\n</ul>\n<p>&nbsp;</p>",
      encumbrance: 0,
      equippedStatus: "equipped",
      gmNotes:
        "<p>Crown of Protection</p>\n<p>Three combined power storage crystals with&nbsp; a combined power of 21.&nbsp;There are also a Protection 4 Matrix and a Spirit Screen 4 Matrix in the Crown</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>",
      id: "m1WS7dwBAieGc7VQ",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Crown (X20) /21 mp",
      physicalItemType: "consumable",
      price: {
        estimated: 0,
        real: 5000,
      },
      quantity: "21",
    },
    {
      attunedTo: "",
      contains: [],
      description:
        "<p>A torch has one end wrapped in cloth and dipped in pitch or a similar flammable substance. It can be lit with fl int and tinder in one round and will burn for two hour. A torch illuminates a three metre radius. If used as a weapon, it is considered a club (wielded with a &ndash;10% penalty), except that it does not infl ict normal damage &ndash; instead, it infl icts 1D4 fire damage and a fumble or critical hit will also extinguish the brand.</p>",
      encumbrance: 1,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "5VM1RdHVhH5yBKDj",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Torches, Wicker 2hrs",
      physicalItemType: "consumable",
      price: {
        estimated: 0.1,
        real: 0.1,
      },
      quantity: 2,
    },
    {
      attunedTo: "",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "0AWfM3btiXFoHLFz",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Magic (Protection 1)",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "NTkX2hh65UH1GBJZ",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Magic (Protection 2)",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "YFEpAHn6KDNwRznf",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Magic (Protection 3)",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "",
      encumbrance: 0,
      equippedStatus: "notCarried",
      gmNotes: "",
      id: "OdsIiSPM8makbpen",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Magic (Protection 4)",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: null,
      encumbrance: 1,
      equippedStatus: "equipped",
      gmNotes: null,
      id: "ePfn4kaBDcZdexrW",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Demo Sword",
      physicalItemType: "unique",
      price: {
        estimated: 10,
        real: 10,
      },
      quantity: 1,
    },
    {
      attunedTo: "",
      contains: [],
      description: "",
      encumbrance: 1,
      equippedStatus: "carried",
      gmNotes: "",
      id: "r5aLbz8kWKrj77qW",
      isVirtual: false,
      isContainer: false,
      location: "",
      name: "Styrke",
      physicalItemType: "unique",
      price: {
        estimated: 0,
        real: 0,
      },
      quantity: 1,
    },
  ],
  description: "",
  encumbrance: 0,
  equippedStatus: "notCarried",
  gmNotes: "",
  id: "virtual:undefined:",
  isVirtual: true,
  isContainer: true,
  location: "",
  name: "",
  physicalItemType: "unique",
  price: {
    estimated: 0,
    real: 0,
  },
  quantity: 1,
};
