export enum ItemTypeEnum {
  Skill = "skill",
  Passion = "passion",
  ElementalRunes = "elementalRunes",
  PowerRunes = "elementalRunes",
  MeleeWeapon = "meleeWeapon",
  MissileWeapon = "missileWeapon",
  Shield = "shield",
  NaturalWeapon = "naturalWeapon",
  Gear = "gear",
  Armor = "armor",
  SpiritMagic = "spiritMagic",
  RuneMagic = "runeMagic",
  SorcerousMagic = "sorcerousMagic",
}
