export enum ItemTypeEnum {
  Skill = "skill",
  Passion = "passion",
  ElementalRune = "elementalRune",
  PowerRune = "powerRune",
  HitLocation = "hitLocation",
  MeleeWeapon = "meleeWeapon",
  MissileWeapon = "missileWeapon",
  Shield = "shield",
  NaturalWeapon = "naturalWeapon",
  Gear = "gear",
  Armor = "armor",
  SpiritMagic = "spiritMagic",
  RuneMagic = "runeMagic",
  SorcerousMagic = "sorcerousMagic",
}
