/**
 * Generates a JSON Schema (draft 2020-12) for each Item/Actor document `type`,
 * derived from the real `defineSchema()` implementations in `src/data-model/**`.
 *
 * This lets downstream tools (e.g. the fvtt-module-wiki-rqg-private compendium-pack
 * build pipeline) validate authored YAML/source content against an up-to-date
 * schema instead of a hand-maintained, loosely-typed one.
 *
 * Usage:
 *   pnpm generate:schemas          Write schema files to src/data-model/json-schemas/generated
 *   pnpm generate:schemas --check  Fail (without writing) if committed output is stale
 *
 * How it works: `installFoundrySchemaShim()` installs a minimal stand-in for
 * `foundry.data.fields` (see `./generate-schema/foundry-schema-shim.ts`) on
 * `globalThis` *before* any DataModel module is imported. Each DataModel's real,
 * unmodified `static defineSchema()` is then called to get its actual field tree,
 * which `./generate-schema/field-to-json-schema.ts` walks into JSON Schema.
 */
import * as path from "path";
import * as fs from "fs";
import { fileURLToPath } from "url";
import chalk from "chalk";
import { installFoundrySchemaShim } from "./generate-schema/foundry-schema-shim.ts";

// Must run before any DataModel module is imported below (they read
// `foundry.data.fields.*` off the global at module-evaluation time).
installFoundrySchemaShim();

const { schemaToJsonSchema } = await import("./generate-schema/field-to-json-schema.ts");
const { allDocumentModels } = await import("./generate-schema/document-model-registry.ts");
type DocumentModelDescriptor =
  (typeof import("./generate-schema/document-model-registry.ts"))["allDocumentModels"][number];

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_OUTPUT_DIR = path.resolve(__dirname, "../src/data-model/json-schemas/generated");
const REPO_SCHEMA_BASE_URL =
  "https://raw.githubusercontent.com/sun-dragon-cult/fvtt-system-rqg/master/src/data-model/json-schemas/generated";

interface CliOptions {
  outDir: string;
  check: boolean;
}

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = { outDir: DEFAULT_OUTPUT_DIR, check: false };
  for (const arg of argv) {
    if (arg === "--check") {
      options.check = true;
    } else if (arg.startsWith("--out=")) {
      options.outDir = path.resolve(arg.slice("--out=".length));
    } else {
      throw new Error(`generate-schema: unknown argument "${arg}"`);
    }
  }
  return options;
}

interface GeneratedFile {
  relativePath: string;
  content: string;
}

const registryDir = path.resolve(__dirname, "generate-schema");

async function buildSchemaFile(descriptor: DocumentModelDescriptor): Promise<GeneratedFile> {
  const absoluteImportUrl = new URL(descriptor.importPath, `file://${registryDir}/`).href;
  const module = (await import(absoluteImportUrl)) as Record<string, unknown>;
  const DataModelClass = module[descriptor.className] as
    { defineSchema?: () => Record<string, unknown> } | undefined;

  if (!DataModelClass || typeof DataModelClass.defineSchema !== "function") {
    throw new Error(
      `generate-schema: "${descriptor.importPath}" does not export "${descriptor.className}" ` +
        "with a static defineSchema().",
    );
  }

  const schema = DataModelClass.defineSchema();
  const relativePath = path.join(
    descriptor.documentType.toLowerCase(),
    `${descriptor.type}.schema.json`,
  );

  const jsonSchema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `${REPO_SCHEMA_BASE_URL}/${relativePath}`,
    title: `RQG ${descriptor.documentType} - ${descriptor.type}`,
    description:
      `Generated JSON Schema for the "${descriptor.type}" ${descriptor.documentType} ` +
      `DataModel's \`system\` data. Source: ${descriptor.importPath.replace("../../", "")}. ` +
      "Do not edit by hand — run `pnpm generate:schemas`.",
    ...schemaToJsonSchema(schema),
  };

  return { relativePath, content: JSON.stringify(jsonSchema, null, 2) + "\n" };
}

function buildManifest(): GeneratedFile {
  const entries = allDocumentModels.map((descriptor: DocumentModelDescriptor) => ({
    documentType: descriptor.documentType,
    type: descriptor.type,
    file: path.join(descriptor.documentType.toLowerCase(), `${descriptor.type}.schema.json`),
  }));
  return {
    relativePath: "manifest.json",
    content:
      JSON.stringify(
        {
          description:
            "Generated by buildScripts/generate-schema.ts — do not edit by hand. " +
            "Lists every generated per-type schema file.",
          schemas: entries,
        },
        null,
        2,
      ) + "\n",
  };
}

async function generateAll(): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];
  for (const descriptor of allDocumentModels as DocumentModelDescriptor[]) {
    files.push(await buildSchemaFile(descriptor));
  }
  files.push(buildManifest());
  return files;
}

function writeFiles(outDir: string, files: GeneratedFile[]): void {
  fs.rmSync(outDir, { recursive: true, force: true });
  for (const file of files) {
    const fullPath = path.join(outDir, file.relativePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, file.content, "utf8");
  }
}

function checkFiles(outDir: string, files: GeneratedFile[]): boolean {
  let upToDate = true;
  const expectedRelativePaths = new Set(files.map((f) => f.relativePath));

  for (const file of files) {
    const fullPath = path.join(outDir, file.relativePath);
    const existing = fs.existsSync(fullPath) ? fs.readFileSync(fullPath, "utf8") : undefined;
    if (existing !== file.content) {
      upToDate = false;
      console.error(chalk.red(`  stale or missing: ${file.relativePath}`));
    }
  }

  if (fs.existsSync(outDir)) {
    for (const entry of fs.readdirSync(outDir, { recursive: true, withFileTypes: true })) {
      if (!entry.isFile()) {
        continue;
      }
      const relativePath = path.relative(outDir, path.join(entry.parentPath, entry.name));
      if (!expectedRelativePaths.has(relativePath)) {
        upToDate = false;
        console.error(chalk.red(`  unexpected leftover file: ${relativePath}`));
      }
    }
  }

  return upToDate;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const files = await generateAll();

  if (options.check) {
    const upToDate = checkFiles(options.outDir, files);
    if (!upToDate) {
      console.error(
        chalk.red(
          "\ngenerate-schema: generated schemas are out of date. Run `pnpm generate:schemas` and commit the result.",
        ),
      );
      process.exit(1);
    }
    console.log(chalk.green("generate-schema: generated schemas are up to date."));
    return;
  }

  writeFiles(options.outDir, files);
  console.log(
    chalk.green(
      `generate-schema: wrote ${files.length} file(s) to ${path.relative(process.cwd(), options.outDir)}`,
    ),
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
