export const calendarSeasons = {
  currentDate: { year: 1624, month: 5, day: 45, seconds: 0 },
  generalSettings: {
    name: "",
    numericRepresentation: null,
    gameWorldTimeIntegration: "mixed",
    showClock: true,
    pf2eSync: true,
    dateFormat: { date: "MMMM DD, YYYY", time: "HH:mm:ss", monthYear: "MMMM YAYYYYYZ" },
    permissions: {
      id: "497a8508",
      name: "",
      numericRepresentation: null,
      viewCalendar: { player: true, trustedPlayer: true, assistantGameMaster: true },
      addNotes: { player: false, trustedPlayer: true, assistantGameMaster: true },
      reorderNotes: { player: false, trustedPlayer: false, assistantGameMaster: false },
      changeDateTime: { player: false, trustedPlayer: false, assistantGameMaster: false },
    },
  },
  leapYearSettings: { rule: "none", customMod: 0 },
  monthSettings: [
    {
      id: "33cff8a9",
      name: "Sea Season",
      abbreviation: "Sea",
      numericRepresentation: 1,
      numericRepresentationOffset: 0,
      numberOfDays: 56,
      numberOfLeapYearDays: 56,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
    {
      id: "7f5f5eeb",
      name: "Fire Season",
      abbreviation: "Fire",
      numericRepresentation: 2,
      numericRepresentationOffset: 0,
      numberOfDays: 56,
      numberOfLeapYearDays: 56,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
    {
      id: "c96851ef",
      name: "Earth Season",
      abbreviation: "Earth",
      numericRepresentation: 3,
      numericRepresentationOffset: 0,
      numberOfDays: 56,
      numberOfLeapYearDays: 56,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
    {
      id: "95b4dd3e",
      name: "Dark Season",
      abbreviation: "Dark",
      numericRepresentation: 4,
      numericRepresentationOffset: 0,
      numberOfDays: 56,
      numberOfLeapYearDays: 56,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
    {
      id: "cfd06507",
      name: "Storm Season",
      abbreviation: "Storm",
      numericRepresentation: 5,
      numericRepresentationOffset: 0,
      numberOfDays: 56,
      numberOfLeapYearDays: 56,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
    {
      id: "f8505d28",
      name: "Sacred Time",
      abbreviation: "Sac",
      numericRepresentation: 6,
      numericRepresentationOffset: 0,
      numberOfDays: 14,
      numberOfLeapYearDays: 14,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: 1,
    },
  ],
  moonSettings: [
    {
      id: "58e84685",
      name: "The Red Moon",
      cycleLength: 7,
      firstNewMoon: { yearReset: "none", yearX: 1, year: 1613, month: 1, day: 6 },
      phases: [
        { name: "Full", length: 1, icon: "full", singleDay: true },
        { name: "Full Half", length: 1, icon: "last-quarter", singleDay: true },
        { name: "Crescent Going", length: 1, icon: "waning-crescent", singleDay: true },
        { name: "Dying", length: 1, icon: "new", singleDay: true },
        { name: "Black", length: 1, icon: "new", singleDay: true },
        { name: "Crescent Coming", length: 1, icon: "waxing-crescent", singleDay: true },
        { name: "Empty Half", length: 1, icon: "first-quarter", singleDay: true },
      ],
      color: "#ff7566",
      cycleDayAdjust: 0.45,
    },
  ],
  noteCategories: [{ name: "Holiday", color: "#148e94", textColor: "#FFFFFF" }],
  seasonSettings: [
    {
      id: "4723648b",
      name: "Fire Season",
      startingMonth: 9,
      startingDay: 1,
      color: "#f59999",
      sunriseTime: 0,
      sunsetTime: 0,
    },
    {
      id: "d3cabceb",
      name: "Earth Season",
      startingMonth: 17,
      startingDay: 1,
      color: "#d9b787",
      sunriseTime: 0,
      sunsetTime: 0,
    },
    {
      id: "5e23d6ea",
      name: "Dark Season",
      startingMonth: 25,
      startingDay: 1,
      color: "#b5b5b5",
      sunriseTime: 0,
      sunsetTime: 0,
    },
    {
      id: "1e92b8ca",
      name: "Storm Season",
      startingMonth: 33,
      startingDay: 1,
      color: "#a8d9ff",
      sunriseTime: 0,
      sunsetTime: 0,
    },
    {
      id: "f689b80e",
      name: "Sacred Time",
      startingMonth: 41,
      startingDay: 1,
      color: "#ffffff",
      sunriseTime: 0,
      sunsetTime: 0,
    },
    {
      id: "f336efb",
      name: "Sea Season",
      startingMonth: 1,
      startingDay: 1,
      color: "#919efd",
      sunriseTime: 0,
      sunsetTime: 0,
    },
  ],
  timeSettings: {
    id: "8fa239b4",
    hoursInDay: 24,
    minutesInHour: 60,
    secondsInMinute: 60,
    secondsInCombatRound: 6,
    gameTimeRatio: 1,
    unifyGameAndClockPause: true,
    updateFrequency: 1,
  },
  weekdaySettings: [
    { abbreviation: "Fr", id: "691e7df", name: "Freezeday", numericRepresentation: 1 },
    { abbreviation: "Wa", id: "83437f40", name: "Waterday", numericRepresentation: 2 },
    { abbreviation: "Cl", id: "874715b7", name: "Clayday", numericRepresentation: 3 },
    { abbreviation: "Wi", id: "48c371a4", name: "Windsday", numericRepresentation: 4 },
    { abbreviation: "Fi", id: "554a79b9", name: "Fireday", numericRepresentation: 5 },
    { abbreviation: "Wi", id: "c1c4f132", name: "Wildday", numericRepresentation: 6 },
    { abbreviation: "Go", id: "8d6df7aa", name: "Godsday", numericRepresentation: 7 },
  ],
  yearSettings: {
    id: "8f02a7bf",
    numericRepresentation: 1624,
    prefix: "",
    postfix: "",
    showWeekdayHeadings: true,
    firstWeekday: 0,
    yearZero: 0,
    yearNames: [],
    yearNamingRule: "default",
    yearNamesStart: 0,
  },
};
