export const calendar = {
  generalSettings: {
    gameWorldTimeIntegration: "mixed",
    showClock: true,
    pf2eSync: true,
    permissions: {
      viewCalendar: {
        player: true,
        trustedPlayer: true,
        assistantGameMaster: true,
      },
      addNotes: {
        player: false,
        trustedPlayer: true,
        assistantGameMaster: true,
      },
      changeDateTime: {
        player: false,
        trustedPlayer: false,
        assistantGameMaster: false,
      },
    },
  },
  leapYearSettings: { rule: "none", customMod: 0 },
  monthSettings: [
    {
      name: "Disorder week",
      numericRepresentation: 1,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Harmony week",
      numericRepresentation: 2,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Death week",
      numericRepresentation: 3,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: true,
      startingWeekday: null,
    },
    {
      name: "Fertility week",
      numericRepresentation: 4,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: true,
      startingWeekday: null,
    },
    {
      name: "Stasis week",
      numericRepresentation: 5,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Movement week",
      numericRepresentation: 6,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Illusion week",
      numericRepresentation: 7,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Truth week",
      numericRepresentation: 8,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Disorder week",
      numericRepresentation: 9,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Harmony week",
      numericRepresentation: 10,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Death week",
      numericRepresentation: 11,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Fertility week",
      numericRepresentation: 12,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Stasis week",
      numericRepresentation: 13,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Movement week",
      numericRepresentation: 14,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Illusion week",
      numericRepresentation: 15,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Truth week",
      numericRepresentation: 16,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Disorder week",
      numericRepresentation: 17,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Harmony week",
      numericRepresentation: 18,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Death week",
      numericRepresentation: 19,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Fertility week",
      numericRepresentation: 20,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Stasis week",
      numericRepresentation: 21,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Movement week",
      numericRepresentation: 22,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Illusion week",
      numericRepresentation: 23,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Truth week",
      numericRepresentation: 24,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Disorder week",
      numericRepresentation: 25,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Harmony week",
      numericRepresentation: 26,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Death week",
      numericRepresentation: 27,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Fertility week",
      numericRepresentation: 28,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Stasis week",
      numericRepresentation: 29,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Movement week",
      numericRepresentation: 30,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Illusion week",
      numericRepresentation: 31,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Truth week",
      numericRepresentation: 32,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Disorder week",
      numericRepresentation: 33,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Harmony week",
      numericRepresentation: 34,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Death week",
      numericRepresentation: 35,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Fertility week",
      numericRepresentation: 36,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Stasis week",
      numericRepresentation: 37,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Movement week",
      numericRepresentation: 38,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Illusion week",
      numericRepresentation: 39,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Truth week",
      numericRepresentation: 40,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Luck week",
      numericRepresentation: 41,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
    {
      name: "Fate week",
      numericRepresentation: 42,
      numericRepresentationOffset: 0,
      numberOfDays: 7,
      numberOfLeapYearDays: 7,
      intercalary: false,
      intercalaryInclude: false,
      startingWeekday: null,
    },
  ],
  moonSettings: [
    {
      name: "Moon",
      cycleLength: 7,
      firstNewMoon: {
        yearReset: "none",
        yearX: 1,
        year: 1613,
        month: 1,
        day: 6,
      },
      phases: [
        { name: "Full", length: 1, icon: "full", singleDay: true },
        {
          name: "Full Half",
          length: 1,
          icon: "last-quarter",
          singleDay: true,
        },
        {
          name: "Crescent Going",
          length: 1,
          icon: "waning-crescent",
          singleDay: true,
        },
        { name: "Dying", length: 1, icon: "new", singleDay: true },
        { name: "Black", length: 1, icon: "new", singleDay: true },
        {
          name: "Crescent Coming",
          length: 1,
          icon: "waxing-crescent",
          singleDay: true,
        },
        {
          name: "Empty Half",
          length: 1,
          icon: "first-quarter",
          singleDay: true,
        },
      ],
      color: "#ff7566",
      cycleDayAdjust: 0.45,
    },
  ],
  seasonSettings: [
    {
      name: "Sea Season",
      startingMonth: 1,
      startingDay: 1,
      color: "#919efd",
      customColor: "",
    },
    {
      name: "Fire Season",
      startingMonth: 9,
      startingDay: 1,
      color: "#f59999",
      customColor: "",
    },
    {
      name: "Earth Season",
      startingMonth: 17,
      startingDay: 1,
      color: "#d9b787",
      customColor: "",
    },
    {
      name: "Dark Season",
      startingMonth: 25,
      startingDay: 1,
      color: "#b5b5b5",
      customColor: "",
    },
    {
      name: "Storm Season",
      startingMonth: 33,
      startingDay: 1,
      color: "#a8d9ff",
      customColor: "",
    },
    {
      name: "Sacred Time",
      startingMonth: 41,
      startingDay: 1,
      color: "#ffffff",
      customColor: "",
    },
  ],
  timeSettings: {
    hoursInDay: 24,
    minutesInHour: 60,
    secondsInMinute: 60,
    gameTimeRatio: 1,
    unifyGameAndClockPause: true,
    updateFrequency: 1,
  },
  weekdaySettings: [
    { name: "Freezeday", numericRepresentation: 1 },
    { name: "Waterday", numericRepresentation: 2 },
    { name: "Clayday", numericRepresentation: 3 },
    { name: "Windsday", numericRepresentation: 4 },
    { name: "Fireday", numericRepresentation: 5 },
    { name: "Wildday", numericRepresentation: 6 },
    { name: "Godsday", numericRepresentation: 7 },
  ],
  yearSettings: {
    numericRepresentation: 999,
    prefix: "",
    postfix: "",
    showWeekdayHeadings: true,
    firstWeekday: 0,
    yearZero: 0,
    yearNames: [],
    yearNamingRule: "default",
    yearNamesStart: 0,
  },
};
