name: Release
on:
  push:
    branches: ["master"]
env:
  SYSTEM_NAME: rqg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2
        with:
          # Fetch all versions for tag/changelog generation
          fetch-depth: 0

      - name: Calculate Version
        id: calculate_version
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Update System Manifest
        id: update_system
        env:
          NEW_VERSION: ${{ steps.calculate_version.outputs.new_version }}
          NEW_TAG: ${{ steps.calculate_version.outputs.new_tag }}
        run: |
          echo "${NEW_VERSION}"
          echo "${NEW_TAG}"
          jq '. + {"version": env.NEW_VERSION, "manifest": (env.GITHUB_SERVER_URL + "/" + env.GITHUB_REPOSITORY + "/releases/download/" + env.NEW_TAG + "/" + "system.json")}' src/system.json > src/_system.json
          mv src/_system.json src/system.json
          jq '. + {"version": env.NEW_VERSION, "download": (env.GITHUB_SERVER_URL + "/" + env.GITHUB_REPOSITORY + "/releases/download/" + env.NEW_TAG + "/" + env.SYSTEM_NAME + "-" + ".zip")}' src/system.json > src/_system.json
          mv src/_system.json src/system.json
          jq '. + {"version": env.NEW_VERSION, "readme": (env.GITHUB_SERVER_URL + "/" + env.GITHUB_REPOSITORY + "/blob/" + env.NEW_TAG + "/" + "readme.md")}' src/system.json > src/_system.json
          mv src/_system.json src/system.json

      - name: Update Changelog
        id: update_changelog
        env:
          CHANGELOG: ${{ steps.calculate_version.outputs.changelog }}
        run: |
          mv CHANGELOG.md _CHANGELOG.md || touch _CHANGELOG.md
          echo "${CHANGELOG}" > CHANGELOG.md
          cat _CHANGELOG.md >> CHANGELOG.md
          rm -f _CHANGELOG.md

      - name: Commit Changes
        id: commit_changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: src/system.json CHANGELOG.md
          message: |
            chore(build): Releasing ${{ steps.calculate_version.outputs.new_tag }}

      - name: Commit Tag
        id: commit_tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dist
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate_version.outputs.new_tag }}
          release_name: Release ${{ steps.calculate_version.outputs.new_tag }}
          body: |
            Changes in this release:
            ${{ steps.calculate_version.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Build Zip
        id: build_zip
        env:
          NEW_TAG: ${{ steps.calculate_version.outputs.new_tag }}
        run: |
          zip -r /tmp/system.zip dist/*

      - name: Upload Release Asset zipfile
        id: upload_release_asset_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/system.zip
          asset_name: ${{ env.SYSTEM_NAME }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset system manifest
        id: upload_release_asset_manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/system.json
          asset_name: system.json
          asset_content_type: application/json
