name: Create PR or Build Release
on:
  push:
    branches:
      - master
permissions: {}
jobs:
  changes:
    uses: sun-dragon-cult/github-workflows/.github/workflows/release-please.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      manifest-file: system.json
      system-name: rqg
